---
- hosts: devops
  become: yes
  become_method: sudo

  tasks:
    - name: Install python3-apt
      package:
        name: python3-apt
        state: present

  roles:
    - geerlingguy.apache

  tasks:
    - name: Copy website index
      copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
